on:
  push:
    branches:
      - main


jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:

      - uses: danielchabr/pr-labels-checker@master
        id: checkLabel
        with:
          hasSome: release:patch,release:major,release:minor
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
